#include <iostream>
#include <string>
#include <vector>
#include <iterator>
#include <cstring>
#include <initializer_list>
using std::cin;
using std::cout;
using std::endl;
using std::string;
using std::vector;
using std::getline;
using std::begin;
using std::end;
using std::initializer_list;